apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifier
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-notifier
  template:
    metadata:
      labels:
        app: argocd-notifier
    spec:
      containers:
      - name: argocd-notifier
        image: trolleksii/shellop:latest
        imagePullPolicy: Always
      - name: logger
        image: trolleksii/requestprinter:latest
        imagePullPolicy: Always
      serviceAccountName: argocd-notifier
